/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idv.freddie.demo

fun main(args: Array<String>) {
    val scriptRuntime = ScripRuntime()
    println(scriptRuntime.eval("""
        fun x(input: Int): Int = input + 3
        x(2)
    """.trimIndent()))
}
