/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idv.freddie.demo

import idv.freddie.demo.model.SimpleApp

fun main(args: Array<String>) {
    val scriptRuntime = ScripRuntime()
    val i = "i"
    val code = """
        import idv.freddie.demo.model.SimpleApp
        import idv.freddie.demo.dsl.*

        app {
          main {
            repeat(5) { i ->
              println("Hello world $$i")
            }
            return@main 0
          }
        }
    """.trimIndent()
    val myApp = scriptRuntime.eval(code)
    (myApp as? SimpleApp)?.run()
}
