/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idv.freddie.demo

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class DslApplication

fun main(args: Array<String>) {
    runApplication<DslApplication>(*args)
}
